spring.application.name=ch09-jdbc-jooq-nosql
spring.datasource.url=jdbc:h2:mem:ch09;DB_CLOSE_DELAY=-1
spring.sql.init.mode=always
spring.jooq.sql-dialect=H2

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mydatabase

spring.data.redis.host=localhost
spring.data.redis.port=6379
